name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main  # Se ejecuta automáticamente cada vez que subes cambios a la rama main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Descargar el código del repositorio
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2. Configurar las credenciales dinámicas de AWS usando los Secrets de GitHub
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    # 3. Autenticarse en Amazon ECR de forma segura
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # 4. Construir la imagen Docker sin caché para asegurar que tome el nuevo nginx.conf
    - name: Build Docker Image
      run: |
        docker build --no-cache -f "Contenedores/Contenedor - frontend/Dockerfile" -t libro-clases-frontend:v2 .

    # 5. Etiquetar la imagen para el registro de AWS ECR
    - name: Tag Image for ECR
      run: |
        docker tag libro-clases-frontend:v2 961575293682.dkr.ecr.us-east-1.amazonaws.com/libro-clases-frontend:v2

    # 6. Subir la imagen empaquetada al registro de ECR
    - name: Push Image to Amazon ECR
      run: |
        docker push 961575293682.dkr.ecr.us-east-1.amazonaws.com/libro-clases-frontend:v2

    # 7. Forzar el despliegue en Amazon ECS para actualizar la tarea en Fargate
    - name: Deploy to Amazon ECS
      run: |
        aws ecs update-service --cluster cluster-libro-clases --service servicio-libro-clases-frontend --force-new-deployment